server:
  applicationConnectors:
    - type: http
      port: 9090
  adminConnectors:
    - type: http
      port: 9091
logging:
  level: INFO
  loggers:
    org.ServerInteractionDemo: DEBUG
swagger:
  resourcePackage: org.ServerInteractionDemo.resources
  title: Network Server
  version: 1.0-SNAPSHOT
  description:
  contact: vedang91@gmail.com
dealServerConfiguration:
  url: http://docker-network
